PerfectSeedApp/Models/Calculator.cs
using System.ComponentModel.DataAnnotations;

namespace PerfectSeedApp.Models
{
    public class Calculator
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Seed { get; set; }
    }
}

PerfectSeedApp/Models/ErrorViewModel.cs
namespace PerfectSeedApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PerfectSeedApp/Models/Seed.cs
using System.ComponentModel.DataAnnotations;

namespace PerfectSeedApp.Models
{
    public class Seed
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string SeedSequence { get; set; }
    }
}

PerfectSeedApp/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using NuGet.Versioning;
using PerfectSeedApp.Data;
using PerfectSeedApp.Models;
using PerfectSeedApp.Services;

namespace PerfectSeedApp.Controllers
{
    public class CalculatorController : Controller
    {
        #region Fields and Properties

        private readonly PerfectSeedService _perfectSeedService;
        private readonly DataBaseContext _db;
        private IList<Seed> _seeds;


        #endregion

        #region Constructors

        public CalculatorController(DataBaseContext db, PerfectSeedService perfectSeedService)
        {
            _db = db;
            _perfectSeedService = perfectSeedService;
        }

        #endregion

        #region Index View

        public IActionResult Index()
        {
            _seeds = _db.SeedsTable.ToList();
            return View(_seeds);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddNextSeed([FromForm] string sequence)
        {
            if (sequence != null && _perfectSeedService.IsSeedValid(sequence))
            {
                Seed seed = new Seed();
                seed.SeedSequence = sequence.ToUpper();
                _db.SeedsTable.Add(seed);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
           
            return RedirectToAction("Index");
        }

        public IActionResult Calculate(string seeds)
        {
            if (string.IsNullOrEmpty(seeds))
            {
                return RedirectToAction("Index");
            }

            _seeds = Newtonsoft.Json.JsonConvert.DeserializeObject<IList<Seed>>(seeds);
            var x = _perfectSeedService.CalculatePerfectSeed(_seeds);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteAll(string seeds)
        {
            if (string.IsNullOrEmpty(seeds))
            {
                return RedirectToAction("Index");
            }

            _seeds = Newtonsoft.Json.JsonConvert.DeserializeObject<IList<Seed>>(seeds);

            foreach (var obj in _seeds)
            {
                _db.SeedsTable.Remove(obj);
            }

            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteOneSeed(string obj)
        {
            var seed = Newtonsoft.Json.JsonConvert.DeserializeObject<Seed>(obj);
            _db.SeedsTable.Remove(seed);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        #endregion

    }
}

PerfectSeedApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PerfectSeedApp.Models;
using System.Diagnostics;

namespace PerfectSeedApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PerfectSeedApp/Views/Calculator/AddSeed.cshtml
@model Seed

<form method="post">
    <h1>Perfect Seed Calculator</h1>
    <div class="container p-3">
        <div class="row p-0">
            <div class="col-9">
                <div class="d-flex align-items-center">
                    <!-- Button "Add next Seed" -->
                    <button type="submit" class="btn btn-primary"> Add Seed </button>
                    
                    <!-- Input box -->
                    <input asp-for="SeedSequence" style="width: 110px" class="input-group-text">
                </div>
            </div>
            <div class="col-3 text-end">
                <!-- Button "Calculate" -->
                <button asp-controller="=Calculator" asp-action="Calculate" class="btn btn-primary">
                    <i class="bi bi-calculator"></i>&nbsp; Calculate
                </button>
            </div>
        </div>
        <br />
    </div>
</form>
    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <th>
                Seed Id
            </th>
            <th>
                Your Seeds
            </th>
        </thead>
        <tbody>
       
        </tbody>
    </table>
    </div>

PerfectSeedApp/Views/Calculator/Index.cshtml
@model IList<Seed>

@{
    ViewData["Title"] = "Index";
}

<h1>Perfect Seed Calculator</h1>

<div class="container p-3">
    <div class="row p-0">
        <div class="col-5">
            <div class="d-flex align-items-center">
              
                <!-- Button "Add next Seed" -->
                <form asp-controller="Calculator" asp-action="AddNextSeed" method="post" class="d-flex align-items-center">
                    <div class="input-group">
                        <button type="submit" class="btn btn-primary" style="width: 180px">
                            <i class="bi bi-database-add"></i>&nbsp; Add next Seed
                        </button>
                        <input type="text" name="sequence" class="form-control" placeholder="Enter Seed" style="width: 125px" required />
                    </div>
                </form>

            </div>
        </div>
        <div class="col-7">
            <div class="d-flex align-items-center">
               
                <!-- Button "Calculate" -->
                <form asp-controller="Calculator" asp-action="Calculate" method="post" >
                    <input type="hidden" name="seeds" value="@Newtonsoft.Json.JsonConvert.SerializeObject(Model)" />
                    <button type="submit" class="btn btn-primary" style="width: 140px">
                        <i class="bi bi-calculator"></i>&nbsp; Calculate
                    </button>
                </form>

                <!-- Button "DeleteAll" -->
                <form asp-controller="Calculator" asp-action="DeleteAll" method="post">
                    <input type="hidden" name="seeds" value="@Newtonsoft.Json.JsonConvert.SerializeObject(Model)" />
                    <button type="submit" class="btn btn-primary" style="width: 200px">
                        <i class="bi bi-trash3"></i>&nbsp; Delete all seeds
                    </button>
                </form>

            </div>
        </div>
    </div>
    <br />

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <th>
            Your Seeds
        </th>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="30%">
                    @obj.SeedSequence
                    
                    <!-- Button "DeleteOneSeed" -->
                    <form asp-controller="Calculator" asp-action="DeleteOneSeed" method="post">
                        <input type="hidden" name="obj" value="@Newtonsoft.Json.JsonConvert.SerializeObject(obj)" />
                        <button type="submit" class="btn btn-primary" style="width: 25px; height: 45px; margin: 0 auto;">
                            <i class="bi bi-trash3"></i>&nbsp;
                        </button>
                    </form>

                </td>
            </tr>
        }
    </tbody>
</table>
</div>

PerfectSeedApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome in RUST genetic calculator!</h1>
    <p>XXXaa</p>
</div>

PerfectSeedApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PerfectSeedApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootswatchTheme.css">
    <link rel="stylesheet" href="~/PerfectSeedApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PerfectSeedApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Index">Calculator</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PerfectSeedApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>